name: Python Package using Conda

on:
  push:
    branches:
    - main
    - release/*

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 13

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: set path
      run: echo "/opt/mambaforge/bin" >> $GITHUB_PATH

    - name: Fetch conda install script
      run: |
        wget https://raw.githubusercontent.com/bioconda/bioconda-common/master/{install-and-set-up-conda,configure-conda,common}.sh

    - name: Set up bioconda-utils
      run: bash install-and-set-up-conda.sh

    - name: Configure conda
      run: bash configure-conda.sh
        

    - name: Install dependencies
      run: |
        conda create -n phabox2 phabox=2.1.11 -c conda-forge -c bioconda -y

    - name: Test PhaBOX utilities
      run: |
        source /opt/mambaforge/bin/activate phabox2
        git clone https://github.com/FuchuanQu/GiantHunter.git
        cd GiantHunter
        python -m pip install .
        cd ..
        wget https://github.com/FuchuanQu/GiantHunter/releases/download/v2.0/gianthunter_db_v1.zip
        unzip gianthunter_db_v1.zip > /dev/null
        gianthunter --contigs example/test.fasta --d gianthunter_db_v1 --out test
        cat test/final_prediction/gianthunter_prediction.tsv
        
